### ISSUE TITLE
Free and Pro should work together, using hooks.

### ISSUE THREAD

**Issue by contactashish13** [awesomemotive/all-in-one-seo-pack#1437]
Currently, pro contains the entire code of free and completely replaces free (only one of them is active). Instead, pro should contain only the code for pro and should extend free's features with hooks so that both plugins will be active.

**Comment by michaeltorbert** [comment]
This is something we've contemplated for a while. We should probably list the pros and cons of both ways.

**Comment by contactashish13** [comment]
Maybe we can list the pro of the current way, anything else is a con for the current method :) That said, I can't think of an advantage. Maybe if you can share why it started off like this - there might have been advantages that were seen in the beginning?

**Comment by EkoJr** [comment]
I've been thinking about this issue as well, and figured I would add some input.

* I believe the intention was to preserve the plugin structure to match the public version. When converting to action and filter hooks as a plugin extension, it may be appear different.
* Another possible reason for it would be for development and debugging reasons. Instead of working from 2 areas, it would be independant.
* Cross Version Compatibility. Prime example would be a current version with an older version.

I am for this feature, but tried to look at it from a different point of view.

I believe creating a draft of the structure would help in order to try to keep some similarities to identify from. I'm not sure how the modules would be shadowed though.

**Comment by michaeltorbert** [comment]
I don't think there originally was a reason. As this was the first mainstream commercial plugin, there wasn't much of a precedent. Paid add-ons didn't exist, so I think it simply never occurred to me at the time. In retrospect it probably would have made more sense.

The only con of switching I can think of is the technical burden. Every Pro user on upgrade would also need the free version installed, ideally with no additional human interaction. This seems like a nightmare.

**Comment by contactashish13** [comment]
>Cross Version Compatibility. Prime example would be a current version with an older version.

@EkoJr fair point about this but this is something that can be easily handled with unit tests and automated checks such as integration with TravisCI.

> Every Pro user on upgrade would also need the free version installed, ideally with no additional human interaction

@michaeltorbert I've used http://tgmpluginactivation.com to take care of this. This shows a notice that mandates dependencies and allows the user to download them.

**Comment by EkoJr** [comment]
Yea, some kind of method implemented to install and activate. Which @contactashish13 just pointed to what I was looking at as well. https://github.com/TGMPA/TGM-Plugin-Activation

The Cross Version Compatibility was just a small example that is an easy fix, but even as a critic, I can't find much reasons.

**Comment by contactashish13** [comment]
@michaeltorbert I'm listing down the steps I feel are needed to accomplish this comprehensively

- [ ] replace all instances of if(AIOSEOPPRO) with hooks similar to #1438 
- [ ] complete #1302 
- [ ] integrate with https://github.com/TGMPA/TGM-Plugin-Activation
- [ ] add unit tests (#1377)
- [ ] integrate with TravisCI for different PHP and WP versions (this will also help in issues such as #1355 that inadvertently raised the minimum version to WP 4.7)

**Comment by EkoJr** [comment]
A few more thoughts did occur to me.

1) When converging over to hooks, and the **pro folder (name) being loaded before the public version**. I suspect would be error prone, and a number of workarounds.
2) Would extending the classes be possible? if so, would it help to follow the file & class structure?

**Comment by contactashish13** [comment]
I don't think folders being loaded before would make a difference since the game is all about hooks. Nothing in free is going to call a class/method directly.

Extended functionality will work through hooks and their priorities can be adjusted accordingly.
